/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 *
 * Generated by: npm run db:types:generate
 * Source: supabase/migrations/*.sql (hash: e6f6a493b7ab5983b9e73a65f35496af681d131bb6e58953d345c7e4995e53d0)
 * Files: 2026011800000_initial_schema.sql, 20260118091714_storage_bucket.sql, 20260119091500_bil_registration.sql, 20260126090000_inbound_orders.sql
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      bil_registration: {
        Row: {
          certificate_id: string | null
          created_at: string
          endpoint: string | null
          error: string | null
          error_details: Json | null
          extraction_id: string
          http_status: number | null
          id: string
          payload_received: Json | null
          payload_sent: Json | null
          processing_time: number | null
          success: boolean
          trigger_source: string
        }
        Insert: {
          certificate_id?: string | null
          created_at?: string
          endpoint?: string | null
          error?: string | null
          error_details?: Json | null
          extraction_id: string
          http_status?: number | null
          id?: string
          payload_received?: Json | null
          payload_sent?: Json | null
          processing_time?: number | null
          success: boolean
          trigger_source: string
        }
        Update: {
          certificate_id?: string | null
          created_at?: string
          endpoint?: string | null
          error?: string | null
          error_details?: Json | null
          extraction_id?: string
          http_status?: number | null
          id?: string
          payload_received?: Json | null
          payload_sent?: Json | null
          processing_time?: number | null
          success?: boolean
          trigger_source?: string
        }
        Relationships: [
          {
            foreignKeyName: 'bil_registration_extraction_id_fkey'
            columns: ['extraction_id']
            isOneToOne: false
            referencedRelation: 'extraction'
            referencedColumns: ['id']
          },
        ]
      }
      extraction: {
        Row: {
          confidence: number | null
          created_at: string
          error: string | null
          extracted_data: Json
          fineness: string | null
          id: string
          image_filename: string | null
          is_active: boolean
          metal: string | null
          original_id: string
          processing_time: number | null
          producer: string | null
          serial_number: string | null
          status: Database['public']['Enums']['extraction_status']
          storage_path: string
          strategy_used: string
          updated_by: string | null
          weight: string | null
          weight_unit: string | null
        }
        Insert: {
          confidence?: number | null
          created_at?: string
          error?: string | null
          extracted_data?: Json
          fineness?: string | null
          id?: string
          image_filename?: string | null
          is_active?: boolean
          metal?: string | null
          original_id: string
          processing_time?: number | null
          producer?: string | null
          serial_number?: string | null
          status?: Database['public']['Enums']['extraction_status']
          storage_path: string
          strategy_used: string
          updated_by?: string | null
          weight?: string | null
          weight_unit?: string | null
        }
        Update: {
          confidence?: number | null
          created_at?: string
          error?: string | null
          extracted_data?: Json
          fineness?: string | null
          id?: string
          image_filename?: string | null
          is_active?: boolean
          metal?: string | null
          original_id?: string
          processing_time?: number | null
          producer?: string | null
          serial_number?: string | null
          status?: Database['public']['Enums']['extraction_status']
          storage_path?: string
          strategy_used?: string
          updated_by?: string | null
          weight?: string | null
          weight_unit?: string | null
        }
        Relationships: []
      }
      order: {
        Row: {
          buyer_name: string | null
          confidence: number | null
          created_at: string
          currency: string | null
          document_date: string
          document_issuer: string
          document_number: string
          document_type: Database['public']['Enums']['order_document_type']
          error: string | null
          extracted_data: Json
          id: string
          is_active: boolean
          order_date: string | null
          order_number: string | null
          original_id: string
          other_charges_amount: number | null
          pdf_filename: string | null
          processing_time: number | null
          seller_name: string | null
          shipping_charges_amount: number | null
          shipping_date: string | null
          status: Database['public']['Enums']['order_status']
          storage_path: string
          strategy_used: string
          subtotal_amount: number | null
          total_amount: number | null
          transaction_type: string | null
          updated_by: string | null
          value_date: string | null
        }
        Insert: {
          buyer_name?: string | null
          confidence?: number | null
          created_at?: string
          currency?: string | null
          document_date: string
          document_issuer: string
          document_number: string
          document_type: Database['public']['Enums']['order_document_type']
          error?: string | null
          extracted_data?: Json
          id?: string
          is_active?: boolean
          order_date?: string | null
          order_number?: string | null
          original_id: string
          other_charges_amount?: number | null
          pdf_filename?: string | null
          processing_time?: number | null
          seller_name?: string | null
          shipping_charges_amount?: number | null
          shipping_date?: string | null
          status?: Database['public']['Enums']['order_status']
          storage_path: string
          strategy_used?: string
          subtotal_amount?: number | null
          total_amount?: number | null
          transaction_type?: string | null
          updated_by?: string | null
          value_date?: string | null
        }
        Update: {
          buyer_name?: string | null
          confidence?: number | null
          created_at?: string
          currency?: string | null
          document_date?: string
          document_issuer?: string
          document_number?: string
          document_type?: Database['public']['Enums']['order_document_type']
          error?: string | null
          extracted_data?: Json
          id?: string
          is_active?: boolean
          order_date?: string | null
          order_number?: string | null
          original_id?: string
          other_charges_amount?: number | null
          pdf_filename?: string | null
          processing_time?: number | null
          seller_name?: string | null
          shipping_charges_amount?: number | null
          shipping_date?: string | null
          status?: Database['public']['Enums']['order_status']
          storage_path?: string
          strategy_used?: string
          subtotal_amount?: number | null
          total_amount?: number | null
          transaction_type?: string | null
          updated_by?: string | null
          value_date?: string | null
        }
        Relationships: []
      }
      order_item: {
        Row: {
          created_at: string
          description: string | null
          fineness: string | null
          form: Database['public']['Enums']['bullion_form']
          id: string
          is_active: boolean
          item: string | null
          item_price: number | null
          metal: Database['public']['Enums']['bullion_metal']
          order_id: string
          original_id: string
          producer: string | null
          quantity: string | null
          raw: Json
          serial_number: string | null
          total_price: number | null
          updated_by: string | null
          weight: string | null
          weight_unit: Database['public']['Enums']['bullion_weight_unit']
        }
        Insert: {
          created_at?: string
          description?: string | null
          fineness?: string | null
          form?: Database['public']['Enums']['bullion_form']
          id?: string
          is_active?: boolean
          item?: string | null
          item_price?: number | null
          metal?: Database['public']['Enums']['bullion_metal']
          order_id: string
          original_id: string
          producer?: string | null
          quantity?: string | null
          raw?: Json
          serial_number?: string | null
          total_price?: number | null
          updated_by?: string | null
          weight?: string | null
          weight_unit?: Database['public']['Enums']['bullion_weight_unit']
        }
        Update: {
          created_at?: string
          description?: string | null
          fineness?: string | null
          form?: Database['public']['Enums']['bullion_form']
          id?: string
          is_active?: boolean
          item?: string | null
          item_price?: number | null
          metal?: Database['public']['Enums']['bullion_metal']
          order_id?: string
          original_id?: string
          producer?: string | null
          quantity?: string | null
          raw?: Json
          serial_number?: string | null
          total_price?: number | null
          updated_by?: string | null
          weight?: string | null
          weight_unit?: Database['public']['Enums']['bullion_weight_unit']
        }
        Relationships: [
          {
            foreignKeyName: 'order_item_order_id_fkey'
            columns: ['order_id']
            isOneToOne: false
            referencedRelation: 'order'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      bullion_form: 'bar' | 'coin' | 'round' | 'unknown'
      bullion_metal: 'gold' | 'silver' | 'platinum' | 'palladium' | 'unknown'
      bullion_weight_unit: 'g' | 'kg' | 'oz' | 'lb' | 'unknown'
      extraction_status: 'pending' | 'validated' | 'corrected' | 'rejected' | 'error'
      order_document_type: 'invoice' | 'order_confirmation' | 'delivery_note' | 'unknown'
      order_status: 'pending' | 'validated' | 'corrected' | 'rejected' | 'error' | 'closed'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      bullion_form: ['bar', 'coin', 'round', 'unknown'],
      bullion_metal: ['gold', 'silver', 'platinum', 'palladium', 'unknown'],
      bullion_weight_unit: ['g', 'kg', 'oz', 'lb', 'unknown'],
      extraction_status: ['pending', 'validated', 'corrected', 'rejected', 'error'],
      order_document_type: ['invoice', 'order_confirmation', 'delivery_note', 'unknown'],
      order_status: ['pending', 'validated', 'corrected', 'rejected', 'error', 'closed'],
    },
  },
} as const
