/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 *
 * Generated by: npm run db:types:generate
 * Source: supabase/migrations/*.sql (hash: 96d2f90ac1ba51b0b5c6dc7a842f395181643f9720abff7bdf70672234dac3a9)
 * Files: 2026011800000_initial_schema.sql, 20260118091714_storage_bucket.sql, 20260119091500_bil_registration.sql
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      bil_registration: {
        Row: {
          certificate_id: string | null
          created_at: string
          endpoint: string | null
          error: string | null
          error_details: Json | null
          extraction_id: string
          http_status: number | null
          id: string
          payload_received: Json | null
          payload_sent: Json | null
          processing_time: number | null
          success: boolean
          trigger_source: string
        }
        Insert: {
          certificate_id?: string | null
          created_at?: string
          endpoint?: string | null
          error?: string | null
          error_details?: Json | null
          extraction_id: string
          http_status?: number | null
          id?: string
          payload_received?: Json | null
          payload_sent?: Json | null
          processing_time?: number | null
          success: boolean
          trigger_source: string
        }
        Update: {
          certificate_id?: string | null
          created_at?: string
          endpoint?: string | null
          error?: string | null
          error_details?: Json | null
          extraction_id?: string
          http_status?: number | null
          id?: string
          payload_received?: Json | null
          payload_sent?: Json | null
          processing_time?: number | null
          success?: boolean
          trigger_source?: string
        }
        Relationships: [
          {
            foreignKeyName: 'bil_registration_extraction_id_fkey'
            columns: ['extraction_id']
            isOneToOne: false
            referencedRelation: 'extraction'
            referencedColumns: ['id']
          },
        ]
      }
      extraction: {
        Row: {
          confidence: number | null
          created_at: string
          error: string | null
          extracted_data: Json
          fineness: string | null
          id: string
          image_filename: string | null
          is_active: boolean
          metal: string | null
          original_id: string
          processing_time: number | null
          producer: string | null
          serial_number: string | null
          status: Database['public']['Enums']['extraction_status']
          storage_path: string
          strategy_used: string
          updated_by: string | null
          weight: string | null
          weight_unit: string | null
        }
        Insert: {
          confidence?: number | null
          created_at?: string
          error?: string | null
          extracted_data?: Json
          fineness?: string | null
          id?: string
          image_filename?: string | null
          is_active?: boolean
          metal?: string | null
          original_id: string
          processing_time?: number | null
          producer?: string | null
          serial_number?: string | null
          status?: Database['public']['Enums']['extraction_status']
          storage_path: string
          strategy_used: string
          updated_by?: string | null
          weight?: string | null
          weight_unit?: string | null
        }
        Update: {
          confidence?: number | null
          created_at?: string
          error?: string | null
          extracted_data?: Json
          fineness?: string | null
          id?: string
          image_filename?: string | null
          is_active?: boolean
          metal?: string | null
          original_id?: string
          processing_time?: number | null
          producer?: string | null
          serial_number?: string | null
          status?: Database['public']['Enums']['extraction_status']
          storage_path?: string
          strategy_used?: string
          updated_by?: string | null
          weight?: string | null
          weight_unit?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      extraction_status: 'pending' | 'validated' | 'corrected' | 'rejected' | 'error'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      extraction_status: ['pending', 'validated', 'corrected', 'rejected', 'error'],
    },
  },
} as const
